### ISSUE TITLE
Do you have a schedule of release?

### ISSUE THREAD

**Issue by olliacc** [hohonu-vicml/TrailBlazer#1]
I read that TrailBlazer's code will be released in January, but I'm unsure about the specific date. Could you provide more details on the release timeline? I'm keen to explore and implement your text-to-video approach and would greatly appreciate access to the code.

Thanks.

**Comment by choasma** [comment]
Ahh! Sorry I was taking a bit holiday after ArXiv released. I'll push myself to see if I can summarize and update the repo this week.

**Comment by aniki-ly** [comment]
Thank you for your excellent work. I am looking forward to the completion of the code.

**Comment by tanchenkai** [comment]
+1

**Comment by choasma** [comment]
Just...  Released :)

Sorry keep you guys waiting. Feel free to contact me if you have any questions :sweat_smile:
