### ISSUE TITLE
error You have exceeded your GPU quota

### ISSUE THREAD

**Issue by AugmentedRealityCat** [hohonu-vicml/TrailBlazer#3]
The HuggingFace demo has ceased working - but until then it was pretty amazing what it could do ! I can't wait for it to work again.

![Screenshot 2024-02-05 at 18-56-24 Trailblazer - a Hugging Face Space by hohonu-vicml](https://github.com/hohonu-vicml/Trailblazer/assets/114955776/6cfaee93-0be2-48ed-a1a9-3acf5287c4bf)

https://huggingface.co/spaces/hohonu-vicml/Trailblazer

**Comment by hohonu-vicml** [comment]
Hey @AugmentedRealityCat, I think you are the same as in our HF community: [https://huggingface.co/spaces/hohonu-vicml/Trailblazer/discussions/2](url). Sorry, this is kinda given HF ZERO gpu grant that the GPU quota is limited.

However, we may try to hire GPU/hardware during AAAI2024 conference in a couple of weeks. Stay tuned!

**Comment by AugmentedRealityCat** [comment]
Yes, that was me as well on HF. Thanks for clarifying the situation. I closed the issue.
