### ISSUE TITLE
Is this similar to Peekaboo?

### ISSUE THREAD

**Issue by TruthSearcher** [hohonu-vicml/TrailBlazer#4]
https://github.com/microsoft/Peekaboo

**Comment by choasma** [comment]
Hi @TruthSearcher,

First of all, we appreciate your feedback and your patience. We believe the answer is affirmative in terms of the overall goal (e.g., bounding box guidance), and the method at a high-level perspective (e.g., attention editing). 

However, there are numerous nuances that differ between the methods in detail. This presents an opportunity for TrailBlazer to conduct comparisons and anticipate future developments. We will notify you here again soon when our next ArXiv version is released and will highlight how TrailBlazer excels in achieving results under specific conditions.

Best,
