### ISSUE TITLE
When will there be support for multiple objects?

### ISSUE THREAD

**Issue by aniki-ly** [hohonu-vicml/TrailBlazer#6]

**Comment by choasma** [comment]
Hello @aniki-ly, 

Thank you for your patience. We're pleased to announce that the multiple objects feature has been released. You can access the commands to utilize this feature [here](https://github.com/hohonu-vicml/Trailblazer/blob/main/doc/Command.md#bincmdtrailblazermultipy), and view the corresponding results [here](https://github.com/hohonu-vicml/Trailblazer/tree/main/config#multi).

If you encounter any issues or have any feedback, please don't hesitate to let us know. We're here to assist you.

Best

**Comment by aniki-ly** [comment]
Hi, @choasma, 

Thank you for your valuable contribution. I'm eager to test the multi-object features!

Best,
